title: R/Pharma Conference
logo: /assets/img/logo.png
description: R/Pharma is an annual conference envisioned as a relatively small, scientifically & industry oriented, collegial event focused on the use of R in the development of pharmaceuticals.
show_downloads: false
logo: /assets/img/logotext_small.png
google_analytics:
theme: jekyll-theme-minimal
